WITH COMPASA_PROD AS (
    SELECT B1_COD, B1_DESC, B1_MSBLQL, R_E_C_N_O_, S_T_A_M_P_
    FROM SB1_CADASTRO_PRODUTO
    WHERE B1_EMPRESA = 'COMPASA DO BRASIL'
    AND D_E_L_E_T_ <> '*'
),
RONCADOR_PROD AS (
    SELECT B1_COD, B1_DESC, B1_MSBLQL, R_E_C_N_O_, S_T_A_M_P_
    FROM SB1_CADASTRO_PRODUTO
    WHERE B1_EMPRESA = 'CONSORCIO RONCADOR'
    AND D_E_L_E_T_ <> '*'
),
COMPASA_FORN AS (
    SELECT A2_COD, A2_LOJA, A2_NOME, A2_MSBLQL, R_E_C_N_O_, S_T_A_M_P_
    FROM SA2_CADASTRO_FORNECEDOR
    WHERE A2_EMPRESA = 'COMPASA DO BRASIL'
      AND D_E_L_E_T_ <> '*'
),
RONCADOR_FORN AS (
    SELECT A2_COD, A2_LOJA, A2_NOME, A2_MSBLQL, R_E_C_N_O_, S_T_A_M_P_
    FROM SA2_CADASTRO_FORNECEDOR
    WHERE A2_EMPRESA = 'CONSORCIO RONCADOR'
      AND D_E_L_E_T_ <> '*'
),
COMPASA_CLI AS (
    SELECT A1_COD, A1_LOJA, A1_NOME, A1_MSBLQL, R_E_C_N_O_, S_T_A_M_P_
    FROM SA1_CADASTRO_CLIENTE
    WHERE EMPRESA = 'COMPASA DO BRASIL'
      AND D_E_L_E_T_ <> '*'
),
RONCADOR_CLI AS (
    SELECT A1_COD, A1_LOJA, A1_NOME, A1_MSBLQL, R_E_C_N_O_, S_T_A_M_P_
    FROM SA1_CADASTRO_CLIENTE
    WHERE EMPRESA = 'CONSORCIO RONCADOR'
      AND D_E_L_E_T_ <> '*'
)
SELECT 
    'PRODUTO' AS TIPO,
    C.B1_COD AS COD_COMPASA, 
    '' AS LOJA_COMPASA, 
    LTRIM(RTRIM(C.B1_DESC)) AS DESC_COMPASA, 
    CASE WHEN C.B1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COMPASA,
    C.R_E_C_N_O_ AS RECNO_COMPASA,
    C.S_T_A_M_P_ AS STAMP_COMPASA,
    ' | ' AS SEP,
    R.B1_COD AS COD_RONCADOR, 
    '' AS LOJA_RONCADOR,
    LTRIM(RTRIM(R.B1_DESC)) AS DESC_RONCADOR,
    CASE WHEN R.B1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_RONCADOR,
    R.R_E_C_N_O_ AS RECNO_RONCADOR,
    R.S_T_A_M_P_ AS STAMP_RONCADOR,
    CASE 
        WHEN C.B1_COD IS NULL OR R.B1_COD IS NULL THEN 'Produto não cadastrado'
        WHEN LTRIM(RTRIM(C.B1_DESC)) <> LTRIM(RTRIM(R.B1_DESC)) THEN 'Valores são diferentes entre as bases'
        ELSE 'Cadastros iguais'
    END AS VALIDACAO
FROM COMPASA_PROD C
LEFT JOIN RONCADOR_PROD R ON C.B1_COD = R.B1_COD

UNION ALL

SELECT 
    'PRODUTO' AS TIPO,
    C.B1_COD AS COD_COMPASA, 
    '' AS LOJA_COMPASA, 
    LTRIM(RTRIM(C.B1_DESC)) AS DESC_COMPASA, 
    CASE WHEN C.B1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COMPASA,
    C.R_E_C_N_O_ AS RECNO_COMPASA,
    C.S_T_A_M_P_ AS STAMP_COMPASA,
    ' | ' AS SEP,
    R.B1_COD AS COD_RONCADOR, 
    '' AS LOJA_RONCADOR,
    LTRIM(RTRIM(R.B1_DESC)) AS DESC_RONCADOR,
    CASE WHEN R.B1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_RONCADOR,
    R.R_E_C_N_O_ AS RECNO_RONCADOR,
    R.S_T_A_M_P_ AS STAMP_RONCADOR,
    CASE 
        WHEN C.B1_COD IS NULL OR R.B1_COD IS NULL THEN 'Produto não cadastrado'
        WHEN LTRIM(RTRIM(C.B1_DESC)) <> LTRIM(RTRIM(R.B1_DESC)) THEN 'Valores são diferentes entre as bases'
        ELSE 'Cadastros iguais'
    END AS VALIDACAO
FROM COMPASA_PROD C
RIGHT JOIN RONCADOR_PROD R ON C.B1_COD = R.B1_COD
WHERE C.B1_COD IS NULL

UNION ALL

SELECT 
    'FORNECEDOR' AS TIPO,
    C.A2_COD AS COD_COMPASA, 
    C.A2_LOJA AS LOJA_COMPASA, 
    LTRIM(RTRIM(C.A2_NOME)) AS DESC_COMPASA, 
    CASE WHEN C.A2_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COMPASA, 
    C.R_E_C_N_O_ AS RECNO_COMPASA,
    C.S_T_A_M_P_ AS STAMP_COMPASA,
    ' | ' AS SEP,
    R.A2_COD AS COD_RONCADOR, 
    R.A2_LOJA AS LOJA_RONCADOR, 
    LTRIM(RTRIM(R.A2_NOME)) AS DESC_RONCADOR, 
    CASE WHEN R.A2_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_RONCADOR, 
    R.R_E_C_N_O_ AS RECNO_RONCADOR,
    R.S_T_A_M_P_ AS STAMP_RONCADOR,
    CASE 
        WHEN C.A2_COD IS NULL OR R.A2_COD IS NULL THEN 'Fornecedor não cadastrado'
        WHEN LTRIM(RTRIM(C.A2_NOME)) <> LTRIM(RTRIM(R.A2_NOME)) THEN 'Valores são diferentes entre as bases'
        ELSE 'Cadastros iguais'
    END AS VALIDACAO
FROM COMPASA_FORN C
LEFT JOIN RONCADOR_FORN R 
    ON C.A2_COD = R.A2_COD 
   AND C.A2_LOJA = R.A2_LOJA

UNION ALL

SELECT 
    'FORNECEDOR' AS TIPO,
    C.A2_COD AS COD_COMPASA, 
    C.A2_LOJA AS LOJA_COMPASA, 
    LTRIM(RTRIM(C.A2_NOME)) AS DESC_COMPASA, 
    CASE WHEN C.A2_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COMPASA, 
    C.R_E_C_N_O_ AS RECNO_COMPASA,
    C.S_T_A_M_P_ AS STAMP_COMPASA,
    ' | ' AS SEP,
    R.A2_COD AS COD_RONCADOR, 
    R.A2_LOJA AS LOJA_RONCADOR, 
    LTRIM(RTRIM(R.A2_NOME)) AS DESC_RONCADOR, 
    CASE WHEN R.A2_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_RONCADOR, 
    R.R_E_C_N_O_ AS RECNO_RONCADOR,
    R.S_T_A_M_P_ AS STAMP_RONCADOR,
    CASE 
        WHEN C.A2_COD IS NULL OR R.A2_COD IS NULL THEN 'Fornecedor não cadastrado'
        WHEN LTRIM(RTRIM(C.A2_NOME)) <> LTRIM(RTRIM(R.A2_NOME)) THEN 'Valores são diferentes entre as bases'
        ELSE 'Cadastros iguais'
    END AS VALIDACAO
FROM COMPASA_FORN C
RIGHT JOIN RONCADOR_FORN R 
    ON C.A2_COD = R.A2_COD 
   AND C.A2_LOJA = R.A2_LOJA
WHERE C.A2_COD IS NULL

UNION ALL

SELECT 
    'CLIENTE' AS TIPO,
    C.A1_COD AS COD_COMPASA, 
    C.A1_LOJA AS LOJA_COMPASA, 
    LTRIM(RTRIM(C.A1_NOME)) AS DESC_COMPASA, 
    CASE WHEN C.A1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COMPASA, 
    C.R_E_C_N_O_ AS RECNO_COMPASA,
    C.S_T_A_M_P_ AS STAMP_COMPASA,
    ' | ' AS SEP,
    R.A1_COD AS COD_RONCADOR, 
    R.A1_LOJA AS LOJA_RONCADOR, 
    LTRIM(RTRIM(R.A1_NOME)) AS DESC_RONCADOR, 
    CASE WHEN R.A1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_RONCADOR, 
    R.R_E_C_N_O_ AS RECNO_RONCADOR,
    R.S_T_A_M_P_ AS STAMP_RONCADOR,
    CASE 
        WHEN C.A1_COD IS NULL OR R.A1_COD IS NULL THEN 'Cliente não cadastrado'
        WHEN LTRIM(RTRIM(C.A1_NOME)) <> LTRIM(RTRIM(R.A1_NOME)) THEN 'Valores são diferentes entre as bases'
        ELSE 'Cadastros iguais'
    END AS VALIDACAO
FROM COMPASA_CLI C
LEFT JOIN RONCADOR_CLI R 
    ON C.A1_COD = R.A1_COD 
   AND C.A1_LOJA = R.A1_LOJA

UNION ALL

SELECT 
    'CLIENTE' AS TIPO,
    C.A1_COD AS COD_COMPASA, 
    C.A1_LOJA AS LOJA_COMPASA, 
    LTRIM(RTRIM(C.A1_NOME)) AS DESC_COMPASA, 
    CASE WHEN C.A1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_COMPASA, 
    C.R_E_C_N_O_ AS RECNO_COMPASA,
    C.S_T_A_M_P_ AS STAMP_COMPASA,
    ' | ' AS SEP,
    R.A1_COD AS COD_RONCADOR, 
    R.A1_LOJA AS LOJA_RONCADOR, 
    LTRIM(RTRIM(R.A1_NOME)) AS DESC_RONCADOR, 
    CASE WHEN R.A1_MSBLQL = '2' THEN 'ATIVO' ELSE 'INATIVO' END AS STATUS_RONCADOR, 
    R.R_E_C_N_O_ AS RECNO_RONCADOR,
    R.S_T_A_M_P_ AS STAMP_RONCADOR,
    CASE 
        WHEN C.A1_COD IS NULL OR R.A1_COD IS NULL THEN 'Cliente não cadastrado'
        WHEN LTRIM(RTRIM(C.A1_NOME)) <> LTRIM(RTRIM(R.A1_NOME)) THEN 'Valores são diferentes entre as bases'
        ELSE 'Cadastros iguais'
    END AS VALIDACAO
FROM COMPASA_CLI C
RIGHT JOIN RONCADOR_CLI R 
    ON C.A1_COD = R.A1_COD 
   AND C.A1_LOJA = R.A1_LOJA
WHERE C.A1_COD IS NULL
ORDER BY 
    TIPO DESC, 
    COALESCE(RECNO_COMPASA, RECNO_RONCADOR) ASC