SELECT
    CASE EMPRESA
        WHEN 'COMPASA DO BRASIL' THEN '01'
        WHEN 'CLL - COMPASA LOGISTICA LTDA' THEN '02'
        WHEN 'CONSORCIO COMPASA - GAISSLER' THEN '03'
        WHEN 'COMPASA - BR-INFRA | RDC4' THEN '04'
        WHEN 'COMPASA - BR-INFRA | RDC6' THEN '05'
        WHEN 'ATS ASFALTOS TECNOLOGIA E SERVIÇOS LTDA' THEN '06'
        WHEN 'CONSORCIO CONSTRUTOR PR-323' THEN '07'
        WHEN 'CONSORCIO CONSTRUTOR CONSERVA-PR' THEN '08'
        WHEN 'VALE DAS PEDRAS' THEN '09'
        WHEN 'CONSORCIO RONCADOR' THEN '10'
        ELSE EMPRESA
    END AS 'CTT_EMPRESA',
    CASE 
        WHEN EMPRESA IN ('CONSORCIO COMPASA - GAISSLER', '03') AND TRIM(CTT_CUSTO) = '60101103' THEN '010102'
        WHEN TRIM(CTT_FILIAL) = '01' THEN '010101'
        WHEN TRIM(CTT_FILIAL) = '02' THEN '020101'
        WHEN TRIM(CTT_FILIAL) = '03' THEN '030101'
        WHEN TRIM(CTT_FILIAL) = '04' THEN '040101'
        WHEN TRIM(CTT_FILIAL) = '05' THEN '050101'
        WHEN TRIM(CTT_FILIAL) = '06' THEN '060101'
        WHEN TRIM(CTT_FILIAL) = '07' THEN '070101'
        WHEN TRIM(CTT_FILIAL) = '08' THEN '080101'
        WHEN TRIM(CTT_FILIAL) = '09' THEN '090101'
        WHEN TRIM(CTT_FILIAL) = '10' THEN '100101'
        WHEN TRIM(CTT_FILIAL) = '11' THEN '110101'
        WHEN TRIM(CTT_FILIAL) = '12' THEN '120101'
        WHEN TRIM(CTT_FILIAL) = '13' THEN '130101'
        ELSE CTT_FILIAL
    END AS CTT_FILIAL,
    CTT_CUSTO,
    CTT_DESC01,
    CASE
        WHEN CTT_BLOQ = '2' THEN 'ATIVO' 
        ELSE 'INATIVO' 
    END AS 'CTT_BLOQ',
    CTT_XFINAN,
    CTT_REGION
FROM CTT_CADASTRO_CENTRO_CUSTO
WHERE D_E_L_E_T_ <> '*'
AND LENGTH(TRIM(CTT_CUSTO)) = 8;