SELECT DISTINCT
B1_COD,
B1_DESC,
B1_UM,
B1_TIPO,
B1_GRUPO,
BM_DESC,
CASE WHEN B1_MSBLQL = '2' THEN 'ATIVO' ELSE 'BLOQUEADO' END AS STATUS
FROM SB1_CADASTRO_PRODUTO
LEFT JOIN SBM_CADASTRO_GRUPO_PRODUTO ON B1_GRUPO = BM_GRUPO
WHERE B1_EMPRESA LIKE 'COMPASA%'
